Oddaja naloge
jaanos/PSA1 pull request #12
Opened 2016-12-23 17:16 UTC by Jan-hexit

Upam da je to pravilen pull request

2016-12-23 23:05 UTC, jaanos requested changes

2016-12-23 23:05 UTC, jaanos commented on naloge/2016/dn1/test.py
> +
Prosil bi te, da to datoteko premakneš v mapo `test/JanPerme/`.

2016-12-24 09:40 UTC, Jan-hexit commented
Ok sem to naredil. Vidim da se ta commit pokaže pod vašim komentarjem. Ali rabim narediti now pull request ali ne?

2016-12-25 13:43 UTC, jaanos approved these changes

2016-12-25 13:44 UTC, jaanos commented
Je v redu - commiti se samodejno dodajo v aktivne pull requeste, tako da bom tega sprejel.

2016-12-25 22:11 UTC, merged